site_name: 二进制新手入门
site_url: https://huoji120.github.io/
repo_url: https://github.com/huoji120/huoji120.github.io
repo_name: huoji120/huoji120.github.io

theme:
  name: material
  language: zh
  palette:
    scheme: slate
    primary: black
    accent: indigo
  features:
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:
  - CrackMe:
      - C++无壳 新手第一個 KeyGenMe/Crackme: crackme/cpp-no-pack-keygenme-crackme.md
  - 恶意软件分析:
      - 0基础分析阶段执行银狐木马(带混淆): malware_analyze/slievr_fox_analyze_1.md
